### PR TITLE
Enable named export for async loading.

### PR DESCRIPTION
**Pull request by Hyperkid123**
```jsx
<ScalprumComponent scope="foo" module="bar" importName="NamedComponent">
```

cc @tumido

### CODE REVIEW

**Comment by florkbr** [comment]
@Hyperkid123 FYI - I think we may want to update our `lint` script in the package.json. I get this running locally:
```bash
> lint
> eslint ./**/*.{ts,tsx,js}


Oops! Something went wrong! :(

ESLint: 8.0.1

You are linting "./node_modules/decimal.js", but all of the files matching the glob pattern "./node_modules/decimal.js" are ignored.

If you don't want to lint these files, remove the pattern "./node_modules/decimal.js" from the list of arguments passed to ESLint.

If you do want to lint these files, try the following solutions:

* Check your .eslintignore file, or the eslintIgnore property in package.json, to ensure that the files are not configured to be ignored.
* Explicitly list the files from this glob that you'd like to lint on the command-line, rather than providing a glob as an argument.
```

If we update to ` "lint": "eslint \"./**/*.{ts,tsx,js}\"",` the problem goes away.

**Review by florkbr — APPROVED** [review]
Code looks good and tested locally and everything works as expected. @Hyperkid123 I'll let you decide if we update the lint script in this PR or a follow up.
Screenshot 2023-10-11 at 10 59 09 AM

**Comment by florkbr** [comment]
@Hyperkid123 I don't have the merge superpowers FWIW :(

**Comment by Hyperkid123** [comment]
Let's do the lint in a follow-up.

**Pull request merged**
